### ISSUE TITLE
ES6 import with TypeScript

### ISSUE THREAD

**Issue by nemanja-tosic** [mauricedb/polly-js#117] opened 2021-01-20 20:08 UTC
We are using TypeScript with `"esModuleInterop": true`.

Importing polly using the default export like so:

```
import polly from 'polly-js';
```

throws `TypeError: polly_js_1.default is not a function` at runtime.

If we try to use a namespace import:

```
import * as polly from 'polly-js';
```

Then we get `TS2349: This expression is not callable. Type 'typeof polly' has no call signatures` during compilation.

Help? :)
Thanks!

**Comment by nemanja-tosic** [comment] 2021-01-21 15:17
The runtime error was coming from tests, which have a project reference to the code in question. The tests did not have `esModuleInterop` set, whereas the project that was referenced did. Adding `esModuleInterop` to tests solved the issue for us. Not sure if there is a better way to address this though.

**Comment by mauricedb** [comment] 2021-01-22 18:24
Ahh, I was about to ask you for a repo because I am using `esModuleInterop` all the time without problems. Guess I can close this then as the problem is solved.

**Closed by mauricedb** 2021-01-22 18:24 UTC
